
name: Update Website

on:
  release:
    types: [published]

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: get node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: checkout 1
        uses: actions/checkout@v2
        with:
          path: website
          repository: IrosTheBeggar/mstream-website
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: checkout 2
        uses: actions/checkout@v2
        with:
          path: mstream
          repository: IrosTheBeggar/mStream
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: ls
      - run: |
          cd website
          VERS=$(node -pe "require('../mstream/package.json').version")
          node -pe "require('../mstream/package.json').version"
          echo "v$(node -pe "require('../mstream/package.json').version")" 
          echo $VERS
          sed -i "s/[1-9]\+[0-9]*\.[0-9]\+\.[0-9]\+/$VERS/g" templates/express.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "action: update server"
          git push


